### ISSUE TITLE
Bump Go to latest compatible version 

### ISSUE THREAD

**Issue by rexagod** [JIITODC/loadbalancer#16]
While upgrading to the latest version, we'd have to make sure that the workflows and dependencies work as expected after they are pointed to the latest compatible version.

**Comment by hitarth01** [comment]
Hey!
I would like to take up this issue. @rexagod, can you please provide me with some starting reference as I have little to no clue of where to begin with.

**Comment by elle-Bee** [comment]
I have bumped it to the latest version. Created a pull request. Please once address it.

**Comment by DelusionalOptimist** [comment]
@hitarth01 since @elle-Bee already raised a PR for this, would you like to look into https://github.com/JIITODC/loadbalancer/issues/18?
