### ISSUE TITLE
Reduce `Backend` service's docker image size

### ISSUE THREAD

**Issue by DelusionalOptimist** [JIITODC/loadbalancer#18]
### Current
The base image of the final `Backend` image ([Dockerfile](https://github.com/JIITODC/loadbalancer/blob/master/Backend/Dockerfile)) is `golang:1.18` which is very heavy in size.

### Improvement
We should consider using multi stage builds in our Dockerfile.
This will help us to build the Go binary in one stage using `go` image and then use a smaller, alpine or distroless base as the final image.

### References
Multi stage builds - https://docs.docker.com/build/building/multi-stage/#use-multi-stage-builds 
Distroless images - https://github.com/GoogleContainerTools/distroless

**Comment by hitarth01** [comment]
@DelusionalOptimist, I would like to work on this issue.

**Comment by elle-Bee** [comment]
@DelusionalOptimist Hey can i look into this issue too?

**Comment by Shreyas220** [comment]
@hitarth01 @elle-Bee  someone already raised a pr for this 
maybe you can work on this issues, comment on those if interested  
#22  
#21
