### ISSUE TITLE
Reading env variable multiple times 

### ISSUE THREAD

**Issue by Shreyas220** [JIITODC/loadbalancer#21]
## Context?

Every time a new container is detected our code reads the environment variable for label in `GetServiceInfo()` function in docker handler.

![image](https://user-images.githubusercontent.com/55346934/197333428-018823ad-fba6-4358-9ae4-0fbff6d02aad.png)

## What's wrong with this?
We get the label not found error for every new container.

We should read the label  only once and store it as variable.

## So what changes can be done?

We can create a new variable in `DockerHandler` struct and use that in  `GetServiceInfo()`

**Comment by Shreyas220** [comment]
Hey @hitarth01 i am assigning this issue to you. ping me on discord if you have any doubts

**Comment by hitarth01** [comment]
Yes, I'm interested.

**Comment by Shreyas220** [comment]
Hey @hitarth01 , how's the progress on this ? Do you need any help ?

**Comment by hitarth01** [comment]
Hi @Shreyas220 , sorry for responding so late.
I've been quite unwell lately. Will get back to it as soon as I'm well, though you can unassign me if needed.
